name: gsr_sandbox-env
channels:
  - defaults
  - conda-forge
dependencies:
  # Add more dependencies as needed
  - python==3.7
  - matplotlib==3.1.0
  - numpy==1.16.4
  - pandas==0.24.2
  - scipy==1.3.0
  - scikit-learn==0.21.2
  - rpy2==2.9.4
  - tzlocal==1.5.1
  - simplegeneric==0.8.1
  - jupyter==1.0.0
  - jupyterlab==1.0.2
  - pip
  - pip:
    # Sometimes, dependencies are not in conda but in PyPI
    - cookiecutter==1.6.0
    - jupytext==1.2.1   # Keep this package for better code reviews!
    - git+https://github.com/quetz-al/quetzal-client.git@v0.3.0#egg=quetzal-client
  # R dependencies
  - r-ggplot2==3.0.0
  - r-ggally==1.4.0
  - r-cowplot
